import Story from "./Body/Story.js";
import Annoying from "./header/annoying.js";
import Search from "./header/console.js";
import Location from "./header/location.js";
import NavBar from "./header/navbar.js";
import Setting from "./header/setting.js";
import Slider from "./Body/Slider.js";
import Mlocation from "./Mheader/Mlocation.js";
import MSearch from "./Mheader/MSearch.js";
import Services from "./Mheader/MServices.js";
import List from "./Body/List.js";
import Incredible from "./Body/Inc.js";
import Ads from "./Body/Ads.js";
import Amazing from "./Body/amazing.js";
import Grouping from "./Body/Grouping.js";
import Partner from "./Body/Partner.js";
import Brands from "./Body/Brands.js";
import Options from "./Body/Options.js";
import OptionsM from "./Body/OptionsM.js";
import Indemand from "./Body/Indemand.js";
import chosen from "./Body/chosen.js";
import Hot from "./Body/Hot.js";
import Blog from "./Body/Blog.js";
import Footer from "./Body/Footer.js";
import "./fixedButton.js";
import Menu from "./Body/Menu.js";
import Tabs from "./Body/Tabs.js";

Annoying();
Setting();
Search();
NavBar();
Location();
Services();
MSearch();
Mlocation();
Story();
Slider();
List();
Incredible();
Ads();
Amazing();
Grouping();
Partner();
Brands();
Options();
OptionsM();
Indemand();
chosen();
Hot();
Blog();
Footer();
Menu();
Tabs();